import type { Metadata } from "next";
import { contentSeries, site } from "@/lib/site";
import { getContent } from "@/lib/content";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Watch",
    description:
        "Watch UKnighted Kingdom's original series — The Light, Grace Under Glitter, It's a Sexy World, and Sexy Church — free on YouTube.",
          alternates: { canonical: "/watch" },
          };

          const DIRECT_VIDEO_EXTENSIONS = [".mp4", ".webm", ".ogg", ".mov", ".m4v"];

          function getYouTubeEmbedUrl(url: string): string | null {
            try {
                const parsed = new URL(url);
                    const host = parsed.hostname.replace(/^www\./, "");
                        if (!host.includes("youtube.com") && !host.includes("youtu.be")) return null;

                            let id: string | null = null;
                                if (host.includes("youtu.be")) {
                                      id = parsed.pathname.slice(1);
                                          } else if (parsed.searchParams.get("v")) {
                                                id = parsed.searchParams.get("v");
                                                    } else if (parsed.pathname.startsWith("/embed/")) {
                                                          id = parsed.pathname.replace("/embed/", "");
                                                              }
                                                                  return id ? `https://www.youtube-nocookie.com/embed/${id}` : null;
                                                                    } catch {
                                                                        return null;
                                                                          }
                                                                          }

                                                                          function isDirectVideoFile(url: string): boolean {
                                                                            try {
                                                                                const parsed = new URL(url);
                                                                                    const path = parsed.pathname.toLowerCase();
                                                                                        return DIRECT_VIDEO_EXTENSIONS.some((ext) => path.endsWith(ext));
                                                                                          } catch {
                                                                                              return false;
                                                                                                }
                                                                                                }

                                                                                                export default async function WatchPage() {
                                                                                                  const content = await getContent();

                                                                                                    return (
                                                                                                        <>
                                                                                                              <section className="gradient-royal py-20 text-paper">
                                                                                                                      <div className="mx-auto max-w-4xl px-6 text-center">
                                                                                                                                <p className="text-xs font-semibold uppercase tracking-widest text-gold-light">Watch</p>
                                                                                                                                          <h1 className="mt-4 font-display text-4xl font-semibold sm:text-5xl">Original series, free to watch</h1>
                                                                                                                                                    <p className="mt-6 text-lg text-paper/80">
                                                                                                                                                                New episodes premiere on our YouTube channel. Subscribe so you never miss a release.
                                                                                                                                                                          </p>
                                                                                                                                                                                    <a
                                                                                                                                                                                                href={site.youtube}
                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                        rel="noopener noreferrer"
                                                                                                                                                                                                                                    className="mt-8 inline-block rounded-full bg-gold px-7 py-3 text-sm font-semibold text-royal hover:bg-gold-light"
                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                          Watch Us on YouTube
                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                        <section className="mx-auto max-w-6xl px-6 py-20">
                                                                                                                                                                                                                                                                                                <div className="grid gap-8 sm:grid-cols-2">
                                                                                                                                                                                                                                                                                                          {contentSeries.map((item) => {
                                                                                                                                                                                                                                                                                                                      const entry = content.videos[item.slug];
                                                                                                                                                                                                                                                                                                                                  const videoUrl = entry?.url || "";
                                                                                                                                                                                                                                                                                                                                              const title = entry?.title?.trim() || item.title;
                                                                                                                                                                                                                                                                                                                                                          const youTubeEmbedUrl = videoUrl ? getYouTubeEmbedUrl(videoUrl) : null;
                                                                                                                                                                                                                                                                                                                                                                      const isDirectVideo = videoUrl ? isDirectVideoFile(videoUrl) : false;

                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                <article key={item.slug} id={item.slug} className="rounded-2xl border border-royal/10 p-8 card-shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                {youTubeEmbedUrl && (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-5 aspect-video overflow-hidden rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <iframe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            src={youTubeEmbedUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title={title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="h-full w-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    allowFullScreen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {!youTubeEmbedUrl && isDirectVideo && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mb-5 aspect-video overflow-hidden rounded-xl bg-black">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <video src={videoUrl} controls className="h-full w-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="font-display text-2xl font-semibold text-royal">{title}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-3 text-muted">{item.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {videoUrl ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href={videoUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="mt-5 inline-block text-sm font-semibold text-rose hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {youTubeEmbedUrl || isDirectVideo ? "Open video" : "Watch episode"} →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href={site.youtube}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="mt-5 inline-block text-sm font-semibold text-rose hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Watch on our channel →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              